function step17_tckgen(workPath, tckParams)
    templateDir = fullfile(workPath, 'fba', 'template');
    cmd = sprintf('tckgen -algorithm %s -angle %f -maxlen %d -minlen %d -power %f %s/wmfod_template.mif -seed_image %s/template_mask.mif -mask %s/template_mask.mif -select %d -cutoff %f %s/tracks_%d.tck -force', ...
        tckParams.algorithm, tckParams.angle, tckParams.maxlen, tckParams.minlen, tckParams.power, ...
        templateDir, templateDir, templateDir, ...
        tckParams.select, tckParams.cutoff, templateDir, tckParams.select);
    system(cmd);
    siftCmd = sprintf('tcksift %s/tracks_%d.tck %s/wmfod_template.mif %s/tracks_%d_sift.tck -term_number %d -force', ...
        templateDir, tckParams.select, templateDir, templateDir, tckParams.select, tckParams.siftNum);
    system(siftCmd);
end
